kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1
metadata:
  name: greeters.example.org
spec:
  group: example.org
  names:
    kind: Greeters
    plural: greeters
    singular: greeter
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            kind:
              type: string
            apiVersion:
              type: string
            metadata:
              type: object
            spec:
              type: object
              properties:
                schedule:
                  type: string
                  pattern: "^\\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}:\\d{2}$"
                message:
                  type: string
              required:
                - schedule
            status:
              type: object
              properties:
                phase:
                  type: string
          required:
            - kind
            - apiVersion
            - metadata
            - spec
      subresources:
        status: {}
