kind: Pod
apiVersion: v1
metadata:
  name: database
  labels:
    app: database
spec:
  containers:
    - name: app
      image: laboys/http-whoami
---
kind: Pod
apiVersion: v1
metadata:
  name: backend
  labels:
    app: backend
spec:
  containers:
    - name: app
      image: laboys/http-whoiami
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - topologyKey: kubernetes.io/hostname # 节点范围
          labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - database
