kind: PodSecurityPolicy
apiVersion: policy/v1beta1
metadata:
  name: psp-default
spec:
  hostPID: false
  hostIPC: false
  hostNetwork: false
  hostPorts:
    - min: 20000
      max: 25000
    - min: 50000
      max: 55000
  runAsUser:
    rule: MustRunAs
    ranges:
      - min: 100
        max: 200
      - min: 1000
        max: 1500
  runAsGroup:
    rule: MustRunAs
    ranges:
      - min: 100
        max: 200
  fsGroup:
    rule: MustRunAs
    ranges:
      - min: 1000
        max: 1500
  supplementalGroups:
    rule: MustRunAs
    ranges:
      - min: 1000
        max: 1500
  privileged: false
  allowedCapabilities:
    - SYS_TIME
  defaultAddCapabilities:
    - CHOWN
  requiredDropCapabilities:
    - SYS_ADMIN
    - SYS_MODULE
  seLinux:
    rule: MustRunAs
    seLinuxOptions: {}
  readOnlyRootFilesystem: true
  volumes:
    - emptyDir
    - configMap
    - downwardAPI
    - secret
    - persistentVolumeClaim
