kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1
metadata:
  name: quickstarts.example.org
spec:
  group: example.org
  names:
    kind: Quickstart
    listKind: QuickstartList
    plural: quickstarts
    singular: quickstart
  scope: Cluster
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          description: "quickstart for crd"
