kind: Pod
apiVersion: v1
metadata:
  name: run-as-privileged
spec:
  containers:
    - name: app
      image: alpine
      command: ["/bin/sh", "-c", "--", "while :; do sleep 1d; done"]
      securityContext:
        privileged: true
