/*
Copyright (c) 2023 Jayson Wang

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/wjiec/programming_k8s/sample_controller/pkg/apis/sample/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// NamespacedResourceLister helps list NamespacedResources.
// All objects returned here must be treated as read-only.
type NamespacedResourceLister interface {
	// List lists all NamespacedResources in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.NamespacedResource, err error)
	// NamespacedResources returns an object that can list and get NamespacedResources.
	NamespacedResources(namespace string) NamespacedResourceNamespaceLister
	NamespacedResourceListerExpansion
}

// namespacedResourceLister implements the NamespacedResourceLister interface.
type namespacedResourceLister struct {
	indexer cache.Indexer
}

// NewNamespacedResourceLister returns a new NamespacedResourceLister.
func NewNamespacedResourceLister(indexer cache.Indexer) NamespacedResourceLister {
	return &namespacedResourceLister{indexer: indexer}
}

// List lists all NamespacedResources in the indexer.
func (s *namespacedResourceLister) List(selector labels.Selector) (ret []*v1alpha1.NamespacedResource, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.NamespacedResource))
	})
	return ret, err
}

// NamespacedResources returns an object that can list and get NamespacedResources.
func (s *namespacedResourceLister) NamespacedResources(namespace string) NamespacedResourceNamespaceLister {
	return namespacedResourceNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// NamespacedResourceNamespaceLister helps list and get NamespacedResources.
// All objects returned here must be treated as read-only.
type NamespacedResourceNamespaceLister interface {
	// List lists all NamespacedResources in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.NamespacedResource, err error)
	// Get retrieves the NamespacedResource from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.NamespacedResource, error)
	NamespacedResourceNamespaceListerExpansion
}

// namespacedResourceNamespaceLister implements the NamespacedResourceNamespaceLister
// interface.
type namespacedResourceNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all NamespacedResources in the indexer for a given namespace.
func (s namespacedResourceNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.NamespacedResource, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.NamespacedResource))
	})
	return ret, err
}

// Get retrieves the NamespacedResource from the indexer for a given namespace and name.
func (s namespacedResourceNamespaceLister) Get(name string) (*v1alpha1.NamespacedResource, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("namespacedresource"), name)
	}
	return obj.(*v1alpha1.NamespacedResource), nil
}
