kind: Pod
apiVersion: v1
metadata:
  name: mysql-use-configmap
spec:
  containers:
    - name: database
      image: mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: database-config
              key: mysql-password
