kind: Service
apiVersion: v1
metadata:
  name: ss-http-whoami
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/name: http-whoami
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: http-whoami
spec:
  replicas: 3
  serviceName: ss-http-whoami
  selector:
    matchLabels:
      app.kubernetes.io/name: http-whoami
  template:
    metadata:
      labels:
        app.kubernetes.io/name: http-whoami
    spec:
      containers:
        - name: app
          image: laboys/http-whoami
          volumeMounts:
            - name: data
              mountPath: /data
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        resources:
          requests:
            storage: 1Mi
        accessModes:
          - ReadWriteOnce
