kind: Pod
apiVersion: v1
metadata:
  name: http-whoami-customer-unready-unreachable
spec:
  containers:
    - name: app
      image: laboys/http-whoami
  tolerations:
    - key: node.kubernetes.io/not-ready
      effect: NoExecute
      operator: Exists
      tolerationSeconds: 600
    - key: node.kubernetes.io/unreachable
      effect: NoExecute
      operator: Exists
      tolerationSeconds: 600
