kind: Pod
apiVersion: v1
metadata:
  name: tool-wrk
  labels:
    app: tool-wrk
    rel: dev
spec:
  containers:
  - name: wrk
    image: williamyeh/wrk
    command: [ "/bin/sh", "-c", "--" ]
    args: [ "while :; do sleep 365d; done" ]
  restartPolicy: Always

