kind: Secret
apiVersion: v1
metadata:
  name: secret-server-config
stringData:
  token: hello-world
  server.key: server-key...
  server.crt: server-pem...
---
kind: Pod
apiVersion: v1
metadata:
  name: secret-server
spec:
  containers:
    - name: web-server
      image: nginx:alpine
      volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
        - name: certs
          mountPath: /etc/nginx/certs
          readOnly: true
    - name: generator
      image: laboys/fortune
      env:
        - name: REQUEST_TOKEN
          valueFrom:
            secretKeyRef:
              name: secret-server-config
              key: token
      volumeMounts:
        - name: html
          mountPath: /var/www
      args:
        - --token
        - "$(REQUEST_TOKEN)"
  volumes:
    - name: html
      emptyDir: {}
    - name: certs
      secret:
        secretName: secret-server-config
        items:
          - key: server.crt
            path: server.crt
          - key: server.key
            path: server.key
