/*
Copyright (c) 2023 Jayson Wang

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"

	v1alpha2 "github.com/wjiec/programming_k8s/sample-controller/pkg/apis/sample/v1alpha2"
	samplev1alpha2 "github.com/wjiec/programming_k8s/sample-controller/pkg/applyconfiguration/sample/v1alpha2"
)

// FakeClusterResources implements ClusterResourceInterface
type FakeClusterResources struct {
	Fake *FakeSampleV1alpha2
}

var clusterresourcesResource = v1alpha2.SchemeGroupVersion.WithResource("clusterresources")

var clusterresourcesKind = v1alpha2.SchemeGroupVersion.WithKind("ClusterResource")

// Get takes name of the clusterResource, and returns the corresponding clusterResource object, and an error if there is any.
func (c *FakeClusterResources) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha2.ClusterResource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(clusterresourcesResource, name), &v1alpha2.ClusterResource{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.ClusterResource), err
}

// List takes label and field selectors, and returns the list of ClusterResources that match those selectors.
func (c *FakeClusterResources) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha2.ClusterResourceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(clusterresourcesResource, clusterresourcesKind, opts), &v1alpha2.ClusterResourceList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha2.ClusterResourceList{ListMeta: obj.(*v1alpha2.ClusterResourceList).ListMeta}
	for _, item := range obj.(*v1alpha2.ClusterResourceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested clusterResources.
func (c *FakeClusterResources) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(clusterresourcesResource, opts))
}

// Create takes the representation of a clusterResource and creates it.  Returns the server's representation of the clusterResource, and an error, if there is any.
func (c *FakeClusterResources) Create(ctx context.Context, clusterResource *v1alpha2.ClusterResource, opts v1.CreateOptions) (result *v1alpha2.ClusterResource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(clusterresourcesResource, clusterResource), &v1alpha2.ClusterResource{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.ClusterResource), err
}

// Update takes the representation of a clusterResource and updates it. Returns the server's representation of the clusterResource, and an error, if there is any.
func (c *FakeClusterResources) Update(ctx context.Context, clusterResource *v1alpha2.ClusterResource, opts v1.UpdateOptions) (result *v1alpha2.ClusterResource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(clusterresourcesResource, clusterResource), &v1alpha2.ClusterResource{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.ClusterResource), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeClusterResources) UpdateStatus(ctx context.Context, clusterResource *v1alpha2.ClusterResource, opts v1.UpdateOptions) (*v1alpha2.ClusterResource, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(clusterresourcesResource, "status", clusterResource), &v1alpha2.ClusterResource{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.ClusterResource), err
}

// Delete takes name of the clusterResource and deletes it. Returns an error if one occurs.
func (c *FakeClusterResources) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(clusterresourcesResource, name, opts), &v1alpha2.ClusterResource{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeClusterResources) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(clusterresourcesResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha2.ClusterResourceList{})
	return err
}

// Patch applies the patch and returns the patched clusterResource.
func (c *FakeClusterResources) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha2.ClusterResource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(clusterresourcesResource, name, pt, data, subresources...), &v1alpha2.ClusterResource{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.ClusterResource), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied clusterResource.
func (c *FakeClusterResources) Apply(ctx context.Context, clusterResource *samplev1alpha2.ClusterResourceApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha2.ClusterResource, err error) {
	if clusterResource == nil {
		return nil, fmt.Errorf("clusterResource provided to Apply must not be nil")
	}
	data, err := json.Marshal(clusterResource)
	if err != nil {
		return nil, err
	}
	name := clusterResource.Name
	if name == nil {
		return nil, fmt.Errorf("clusterResource.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(clusterresourcesResource, *name, types.ApplyPatchType, data), &v1alpha2.ClusterResource{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.ClusterResource), err
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *FakeClusterResources) ApplyStatus(ctx context.Context, clusterResource *samplev1alpha2.ClusterResourceApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha2.ClusterResource, err error) {
	if clusterResource == nil {
		return nil, fmt.Errorf("clusterResource provided to Apply must not be nil")
	}
	data, err := json.Marshal(clusterResource)
	if err != nil {
		return nil, err
	}
	name := clusterResource.Name
	if name == nil {
		return nil, fmt.Errorf("clusterResource.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(clusterresourcesResource, *name, types.ApplyPatchType, data, "status"), &v1alpha2.ClusterResource{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.ClusterResource), err
}
