kind: Deployment
apiVersion: apps/v1
metadata:
  name: website-controller
spec:
  selector:
    matchLabels:
      controller: website
  template:
    metadata:
      labels:
        controller: website
    spec:
      containers:
        - name: controller
          image: example.com/website
      serviceAccountName: controller-website
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: controller:website
subjects:
  - kind: ServiceAccount
    name: controller-website
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluser-admin
