kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1
metadata:
  name: websites.example.com
spec:
  scope: Namespaced
  group: example.com
  names:
    kind: Website
    plural: websites
    singular: website
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                gitRepo:
                  type: string
                domain:
                  type: string
