/*
Copyright (c) 2023 Jayson Wang

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package applyconfiguration

import (
	schema "k8s.io/apimachinery/pkg/runtime/schema"

	v1alpha1 "github.com/wjiec/programming_k8s/sample-controller/pkg/apis/sample/v1alpha1"
	v1alpha2 "github.com/wjiec/programming_k8s/sample-controller/pkg/apis/sample/v1alpha2"
	samplev1alpha1 "github.com/wjiec/programming_k8s/sample-controller/pkg/applyconfiguration/sample/v1alpha1"
	samplev1alpha2 "github.com/wjiec/programming_k8s/sample-controller/pkg/applyconfiguration/sample/v1alpha2"
)

// ForKind returns an apply configuration type for the given GroupVersionKind, or nil if no
// apply configuration type exists for the given GroupVersionKind.
func ForKind(kind schema.GroupVersionKind) interface{} {
	switch kind {
	// Group=sample.example.org, Version=v1alpha1
	case v1alpha1.SchemeGroupVersion.WithKind("ClusterResource"):
		return &samplev1alpha1.ClusterResourceApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ClusterResourceSpec"):
		return &samplev1alpha1.ClusterResourceSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ClusterResourceStatus"):
		return &samplev1alpha1.ClusterResourceStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("NamespacedResource"):
		return &samplev1alpha1.NamespacedResourceApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("NamespacedResourceSpec"):
		return &samplev1alpha1.NamespacedResourceSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("NamespacedResourceStatus"):
		return &samplev1alpha1.NamespacedResourceStatusApplyConfiguration{}

		// Group=sample.example.org, Version=v1alpha2
	case v1alpha2.SchemeGroupVersion.WithKind("ClusterResource"):
		return &samplev1alpha2.ClusterResourceApplyConfiguration{}
	case v1alpha2.SchemeGroupVersion.WithKind("ClusterResourceSpec"):
		return &samplev1alpha2.ClusterResourceSpecApplyConfiguration{}
	case v1alpha2.SchemeGroupVersion.WithKind("ClusterResourceStatus"):
		return &samplev1alpha2.ClusterResourceStatusApplyConfiguration{}
	case v1alpha2.SchemeGroupVersion.WithKind("NamespacedResource"):
		return &samplev1alpha2.NamespacedResourceApplyConfiguration{}
	case v1alpha2.SchemeGroupVersion.WithKind("NamespacedResourceSpec"):
		return &samplev1alpha2.NamespacedResourceSpecApplyConfiguration{}
	case v1alpha2.SchemeGroupVersion.WithKind("NamespacedResourceStatus"):
		return &samplev1alpha2.NamespacedResourceStatusApplyConfiguration{}

	}
	return nil
}
