kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: database-from-namespace
spec:
  podSelector:
    matchLabels:
      app: database
  ingress:
    - from:
        - namespaceSelector:
            - matchLabels:
                user: alice
      ports:
        - port: 3306
        - port: 5432
