kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: webserver-cidr
spec:
  podSelector:
    matchLabels:
      app: webserver
  ingress:
    - from:
        - ipBlock:
            cidr: 10.0.0.0/16
  egress:
    - to:
        - ipBlock:
            cidr: 10.0.1.0/24
