kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-delete-data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /tmp/pv-delete
