kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-retain-data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp/pv-retain
