kind: Pod
apiVersion: v1
metadata:
  name: pvc-cache-redis
spec:
  containers:
    - name: app
      image: alpine
      ports:
        - name: redis
          containerPort: 6379
          protocol: TCP
      volumeMounts:
        - name: cache
          mountPath: /cache
      command: ["/bin/sh", "-c", "--", "while :; do sleep 1d; done"]
  volumes:
    - name: cache
      persistentVolumeClaim:
        claimName: cache-pvc
