# permissions for end users to edit rules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: rule-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: discovery
    app.kubernetes.io/part-of: discovery
    app.kubernetes.io/managed-by: kustomize
  name: rule-editor-role
rules:
- apiGroups:
  - discovery.example.org
  resources:
  - rules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - discovery.example.org
  resources:
  - rules/status
  verbs:
  - get
